server:
  port: 8888 # 服务端口

eureka:
  instance:
    hostname: localhost # 设置主机名
  client:
    registerWithEureka: false # 是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: false
  #server:
    #waitTimeInMsWhenSyncEmpty: 0 # 设置同步为空时的等待时间。默认 5 * MINUTES